version: "3"
services:
  mongo_fitcon:
    image: mongo:latest
    container_name: mongo_bookstore
    volumes:
      - mongo-db:/data/db
    ports:
      - "27018:27017"
      
  # api-server:
  #   image: api-server
  #   ports:
  #     - "4000:4000"
  #   env_file: ./.env
  #   environment: 
  #     - MONGO_URI=$MONGO_URI
    

  # api-client:
  #   image: api-client
  #   ports:
  #     - "3000:3000"
volumes:
  mongo-db:
   driver: local
